### ISSUE TITLE
Wrong BBCode format for images used.

### ISSUE THREAD

**Issue by SKevo18** [botfactoryit/flarum-imgur-upload#2]
Your extension is wonderful, it works and uploads images, but it uses old BBCode format to insert images and they aren't displayed (`[URL=url][IMG]https://i.imgur.com/xz91mRJ.gif[/IMG][/URL]`, but it should be `![alt text](url)`). The problem is that when you use the old format, images won't display at all. You can also send only plain URL, this works too.

If you are still maintaining this, please modify your code a little to provide the right BBCode! 
Thank you very much!

**Comment by matteocontrini** [comment]
Hi, you're comparing BBCode with Mardown, two different ways for formatting content with Flarum. There's no wrong or right BBCode, it's just a choice of which of the two should be used :)

Make sure you have the BBCode extension enabled.

**Comment by SKevo18** [comment]
I have the BBCode enabled, however the images are not displaying at FreeFlarum
My forum is using https://github.com/flarum/bbcode. I think there should be at least option to automatically format it by using BBCode or Markdown.

**Comment by matteocontrini** [comment]
I've just tried to use the extension on FreeFlarum and I'm not having any issues. Could you provide a link to a page that has this issue?

**Comment by SKevo18** [comment]
I think I've sent a reply here earlier, saying it works now. No idea why it was not sent.

**Comment by matteocontrini** [comment]
You wrote it in the wrong place (#3) 😉
