### ISSUE TITLE
can't open plug-in's settings

### ISSUE THREAD

**Issue by github0null** [botfactoryit/flarum-imgur-upload#6]
Hello ! This is a great feature ! 

But i can't open plug-in's settings by click "open settings" button，it printed some error on console. 

And the image cannot be uploaded.

I tried to uninstall and reinstall, but it still looked like this.

![image](https://user-images.githubusercontent.com/43022536/103087224-b89b9080-4621-11eb-9a75-7c5a4090fa38.png)

**Comment by matteocontrini** [comment]
Hi, this extension is not compatible with beta15 currently. Please follow the discussion on Discuss.flarum.org for updates ;)
