### ISSUE TITLE
Support many Imgur api to upload pictures?

### ISSUE THREAD

**Issue by gamerthundertv** [botfactoryit/flarum-imgur-upload#7]
Hi, you can support list api Imgur with upload pictures?

**Comment by matteocontrini** [comment]
Could you clarify the question? What do you mean with list API?

**Comment by gamerthundertv** [comment]
When an API Imgur Client ID uploads 50 images in 1 hour, that API will not be able to send more images, but another API can send, I want to create an API list when an API cannot post images, the backup API will post picture.

**Comment by matteocontrini** [comment]
I'm afraid I won't be doing this, rate limits are there for a reason and I won't be implementing workarounds to get around rules. Imgur provides a commercial API for these requirements, by the way.
