### ISSUE TITLE
Bundled translations maintenance status

### ISSUE THREAD

**Issue by rob006** [botfactoryit/flarum-imgur-upload#9]
What is the status of translations provided in https://github.com/matteocontrini/flarum-imgur-upload/tree/master/locale? I'm trying to cleanup redundant translations from [Weblate](https://weblate.rob006.net/projects/flarum/) - if translation for given language is already bundled with extension, there is no sense to have it duplicated in Weblate. But this is true only for actively maintained translations, which usually means only translations maintained by extension author. For example if extension author knows Italian, he can provide `en` and `it` translations, while the rest should probably be handled inside of respective language packs. So now I'm trying to figure out which translations are available because of extension author knows this language and will be able to maintain them, and which are just leftovers from old days where translations were contributed by community to extensions instead of language packs (in that case translations may become outdated after some times, since nobody will update them).

So how does it looks like for https://github.com/matteocontrini/flarum-imgur-upload/tree/master/locale? Which languages do you know and will be able to update if any change will be needed? I see that you made some Italian translations, but it is still lagging behind English.

**Comment by matteocontrini** [comment]
Hi, I maintain English and Italian, the other ones are likely to get out of sync.

I'll update Italian, I think I forgot to do that.

Should I then remove the other translation files?

Thanks!

**Comment by rob006** [comment]
> Should I then remove the other translation files?

I'm not sure. Neither Hungarian nor Russian are available on Weblate, so I don't know if your extension is translated in respective language pack. Personally I would remove them just to make clear that these languages are not supported anymore and translations should be handled by language packs. But this could be treated as a BC break, so you could wait for next major release with that.

Anyway, my question was answered, so feel free to close this issue. I'll remove Italian from Weblate and keep other languages for your extension.

**Comment by matteocontrini** [comment]
Thanks!
